### ISSUE TITLE
signup issue

### ISSUE THREAD

**Issue by AdamArcher40** [Joylal4896/sih-Centralized-Grievance-Readdressal-System#1]
when i try to signup an error occurs no internet connection and i am unable to even signup

**Comment by Joylal4896** [comment]
@AdamArcher40 you will need to host the back-end rails application somewhere and point the android app to the url. You will need to change the`SERVER` variable in [this](https://github.com/Joylal4896/sih-Centralized-Grievance-Readdressal-System/blob/738504e50935811bc990c4c08a1422230302970b/android-app/UsersApp/app/src/main/java/com/example/pari/usersapp/Constants.java) file.

PS: this project is not maintained and we won't be able to fix any issues or add features in future.
